- name: Functions (fitlers)
  hosts: local
  connection: local
  become: yes
  vars:
    technologies: html, css, javascript
  tasks:
  - name: default
    ansible.builtin.debug:
      msg: "{{salary | default(50000)}}"
  
  - name: string to list
    ansible.builtin.debug:
      msg: "{{technologies | split(',')}}"

