- name: Functions (fitlers)
  hosts: local
  connection: local
  become: yes
  vars:
    tools_arr:
    - key: frontend
      value: html
    - key: backend
      value: java
  tasks:
  
  - name: items to dictionary
    ansible.builtin.debug:
      msg: "{{tools_arr | items2dict}}"

