- name: Functions (fitlers)
  hosts: local
  connection: local
  vars_files:
  - mysql_password.yaml
  tasks:
  - name: print mysql password from vault
    ansible.builtin.debug:
      msg: "{{mysql_password}}"