- name: Functions (fitlers)
  hosts: local
  connection: local
  become: yes
  vars:
    tools_arr:
    - "{frontend: html}"
    - "{backend: java}"
  tasks:
  
  - name: items to dictionary
    ansible.builtin.debug:
      msg: "{{tools_arr | items2dict}}"

