- name: Verification
  hosts: local
  connection: local
  become: yes
  vars_prompt:
  - name: name
    prompt: what is your name?
    private: false
    
  - name: age
    prompt: what is your age?
    private: true

  tasks:
  - name: Major or Minor Verification
    ansible.builtin.debug:
      msg: "{{name}} is a MAJOR"
    when: age | int >= 18

