- name: variables
  hosts: local
  connection: local
  become: yes
  vars_files:
  - variables.yaml
  vars:
    name: vinay
    course: bca
    roll: 31

  tasks:
  - name: student information
    vars:
      name: siva
    ansible.builtin.debug:
      msg: "This is {{name}} studying {{course}} with roll no {{roll}}"



# playlevel variables done
# task level variables done
# cli arguments done
