- name: Functions (fitlers)
  hosts: local
  connection: local
  become: yes
  vars:
    tools:
      frontend: html
      backend: java
    tools_arr:
    - el1
    - el2
    - el3
  tasks:
  - name: dictionary to items
    ansible.builtin.debug:
      msg: "{{tools | dict2items}}"
  
  - name: items to dictionary
    ansible.builtin.debug:
      msg: "{{tools_arr | items2dict}}"

